version: "3.8"
services:
  cache:
    image: redis
    container_name: notifier_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  mongo:
    image: mongo
    container_name: notifier_mongo
    restart: always
    ports:
      - "27023:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  cache:
    driver: local
